spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: dbuser
    password: dbuser
    driver-class-name: oracle.jdbc.OracleDriver
    jpa:
      show-sql: true
      generate-ddl: true
      database: oracle

        #jpa:
        #open-in-view: true
        #hibernate:
      #dialect: org.hibernate.dialect.Oracle12cDialect
      #ddl-auto: create-drop
      #      ddl-auto: create-drop
      #      ddl-auto: validate

      #datasource:
      #url: jdbc:oracle:thin:@//oracle-db:1521:XEPDB1
      #username: dbuser
      #password: dbuser
      #driver-class-name: oracle.jdbc.OracleDriver

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  application:
    name: service-c
  profiles:
    active: "dev"

---

spring:
  profiles: dev
server:
  port : 8083

---

spring:
  profiles: prod
server:
  port : 8080