spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: dbuser
    password: dbuser
    driver-class-name: oracle.jdbc.OracleDriver
    jpa:
      show-sql: true
      generate-ddl: true
      database: oracle
  application:
    name: service-b
  profiles:
    active: "dev"

---

spring:
  profiles: dev
server:
  port : 8082

---

spring:
  profiles: prod
server:
  port : 8080